import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import WalletConnect from "@/components/WalletConnect";
import { WagmiConfig, createConfig, configureChains } from "wagmi";
import { polygonZkEvmTestnet, scrollSepolia } from "wagmi/chains";
import { publicProvider } from "wagmi/providers/public";
const inter = Inter({ subsets: ["latin"] });

const { chains, publicClient, webSocketPublicClient } = configureChains(
  [polygonZkEvmTestnet, scrollSepolia],
  [publicProvider()]
);

const config = createConfig({
  autoConnect: true,
  publicClient,
  webSocketPublicClient,
});

export default function Home() {
  // Check if the current chain is either Scroll Sepolia or Polygon zkEVM testnet
  const isValidChain = chains.find(
    (chain) =>
      chain.network === "polygon-zkevm-testnet" ||
      chain.network === "scroll-sepolia"
  );

  if (!isValidChain) {
    // Redirect or show an error message indicating the user is on an invalid chain
    return (
      <div>
        You are on an invalid chain. Please switch to Scroll Sepolia or Polygon
        zkEVM testnet.
      </div>
    );
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WagmiConfig config={config}>
        <div>Protecc Yourself</div>
        <WalletConnect />
      </WagmiConfig>
    </>
  );
}
